local fake = require("tests.fake_wezterm")
local layout = require("codex_statusline.layout")
local count = 0
local function eq(a, b, label) assert(a == b, (label or "comparison") .. ": " .. tostring(a) .. " ~= " .. tostring(b)) end
local function test(name, fn)
  fn()
  count = count + 1
  print("PASS " .. name)
end
local function start(options)
  local h = fake.new(options)
  h:start()
  h:settle()
  assert(h:status(), table.concat(h.logs, "\n"))
  return h
end

test("local status preserves right pane and focus", function()
  local h = fake.new()
  local right = h:split(h.main)
  local height = right.dimensions.viewport_rows
  h:start()
  h:settle()
  assert(h:status())
  eq(h:status().dimensions.cols, h.main.dimensions.cols)
  eq(right.dimensions.viewport_rows, height)
  eq(h.tab:active_pane(), right)
  eq(h.splits[2].args.top_level, false)
  h:settle()
  eq(#h.close_commands, 0)
  h:assert_no_errors()
end)

test("two Codex owners do not close each other's status", function()
  local h = fake.new()
  local right = h:split(h.main)
  h:start()
  h:start(right)
  h:settle()
  h:settle()
  assert(h:status() and h:status(right))
  assert(h:status() ~= h:status(right))
  h:shell(right)
  h:settle()
  eq(h.close_commands[1][6], tostring(h:status(right).id))
  h:complete_close(1)
  h:settle()
  assert(h:status())
  eq(h:status(right), nil)
  h:assert_no_errors()
end)

test("split after status defers repair without changing user geometry", function()
  local h = start()
  local status = h:status()
  h:split(h.main)
  local signature = layout.signature(h.tab:panes_with_info())
  h:settle()
  h:settle()
  eq(h:status(), status)
  eq(layout.signature(h.tab:panes_with_info()), signature)
  eq(#h.close_commands, 0)
  eq(h:binding().deferred, "preserve-user-layout")
end)

test("debounce restarts on every changed layout", function()
  local h = fake.new()
  h:start()
  for i = 1, 8 do h.tab.height = 40 + i; h:tick(0.25) end
  eq(#h.splits, 0)
  h:tick(0.75)
  eq(#h.splits, 0)
  h:tick(0.25)
  eq(#h.splits, 1)
end)

test("dragged status height is preserved while content repaints", function()
  local h = start()
  local status = h:status()
  local renders = status.inject_count
  h.tab.root.ratio = 0.7
  h:settle()
  assert(status.dimensions.viewport_rows > 2)
  eq(#h.close_commands, 0)
  assert(status.inject_count > renders)
end)

test("simple migration waits for confirmed close and fresh debounce", function()
  local h = start()
  local old = h:status()
  h.tab.root.axis = "Right"
  h:settle()
  assert(#h.close_commands >= 1)
  eq(#h.splits, 1)
  h:complete_close(1)
  h:tick()
  eq(#h.splits, 1)
  h:settle()
  assert(h:status() and h:status() ~= old)
  eq(#h.splits, 2)
  h:assert_no_errors()
end)

test("unknown process snapshot retains the binding indefinitely", function()
  local h = start()
  local status = h:status()
  local data = h.wezterm.GLOBAL.codex_statusline_state.panes[tostring(h.main.id)]
  local cwd = data.codex_cwd_norm
  assert(cwd)
  h.main.mode, h.main.title = "unknown", "pwsh.exe"
  h:tick(30)
  h:tick(30)
  eq(h:status(), status)
  eq(#h.close_commands, 0)
  eq(data.codex_cwd_norm, cwd)
  h:assert_no_errors()
end)

test("explicit exit observes grace and targets only its status", function()
  local h = start({ bottom_pane = { close_grace_seconds = 2 } })
  h:shell()
  h:tick(1)
  h:tick(1)
  eq(#h.close_commands, 0)
  h:tick(1)
  eq(#h.close_commands, 1)
  eq(h.close_commands[1][6], tostring(h:status().id))
  h:complete_close(1)
  h:tick()
  eq(h:status(), nil)
  assert(h.panes[h.main.id])
end)

test("restart inside grace reuses status", function()
  local h = start({ bottom_pane = { close_grace_seconds = 2 } })
  local status = h:status()
  h:shell()
  h:tick(1)
  h:start()
  h:settle()
  eq(h:status(), status)
  eq(#h.close_commands, 0)
end)

test("rapid restart does not overlap asynchronous status generations", function()
  local h = start()
  local old = h:status()
  h:shell()
  h:tick(1)
  h:start()
  h.main.title = "pwsh.exe"
  h:settle()
  eq(#h.splits, 1)
  h:complete_close(1)
  h:settle()
  assert(h:status() and h:status() ~= old)
  h:complete_close(1)
  h:tick()
  assert(h:status())
end)

test("long delayed close stops retrying and never spawns duplicate", function()
  local h = start()
  h:shell()
  h:tick(1)
  h:start()
  h:tick(11)
  local commands = #h.close_commands
  h:tick(30)
  eq(#h.close_commands, commands)
  eq(#h.splits, 1)
  h:complete_close(1)
  h:settle()
  assert(h:status())
end)

test("transient mux errors retain exact ownership", function()
  local h = start()
  local status = h:status()
  h.lookup_errors = 100
  h:settle()
  eq(h:status(), status)
  eq(#h.splits, 1)
  eq(#h.close_commands, 0)
  h.lookup_errors = 0
  h:settle()
  eq(h:status(), status)
end)

test("manual close stays hidden across reload and can be restored", function()
  local h = start()
  h:remove(h:status())
  h:settle()
  eq(h:status(), nil)
  h:reload()
  h:settle()
  eq(h:status(), nil)
  h.callbacks["codex-statusline-show"](h.window, h.main)
  h:settle()
  assert(h:status())
end)

test("new Codex process restores a manually hidden status", function()
  local h = start()
  h:remove(h:status())
  h:settle()
  h:start()
  h:settle()
  assert(h:status())
end)

test("zoom pauses creation and layout repairs", function()
  local h = fake.new()
  h:start()
  h.tab.zoomed = true
  h:settle()
  eq(#h.splits, 0)
  h.tab.zoomed = false
  h:settle()
  local status = h:status()
  assert(status)
  h.tab.zoomed = true
  h:settle()
  eq(h:status(), status)
  eq(#h.close_commands, 0)
end)

test("small panes wait for space", function()
  local h = fake.new()
  h.tab.height = 6
  h:start()
  h:settle()
  eq(#h.splits, 0)
  h.tab.height = 20
  h:settle()
  assert(h:status())
end)

test("user focus change during split is not overwritten", function()
  local h = fake.new()
  local right = h:split(h.main)
  h.main:activate()
  h.on_split = function() right:activate() end
  h:start()
  h:settle()
  eq(h.tab:active_pane(), right)
end)

test("clicking status returns to its own owner", function()
  local h = start()
  h:status():activate()
  h:tick()
  eq(h.tab:active_pane(), h.main)
end)

test("background owner exits without selecting its tab", function()
  local h = start()
  local tab = h:add_tab()
  h.active_tab = tab
  h:shell()
  h:tick(2)
  eq(#h.close_commands, 1)
  h:complete_close(1)
  h:tick()
  eq(h:status(), nil)
  eq(h.active_tab, tab)
end)

test("owner moved to a new tab retires its old status first", function()
  local h = start()
  local old = h:status()
  h.active_tab = h:move(h.main)
  h:settle()
  eq(h.close_commands[1][6], tostring(old.id))
  h:complete_close(1)
  h:settle()
  assert(h:status() and h:status():tab() == h.active_tab)
end)

test("owner deletion cleans only the owned status", function()
  local h = start()
  local status = h:status()
  h:remove(h.main)
  h:tick()
  eq(h.close_commands[1][6], tostring(status.id))
  h:complete_close(1)
  h:tick()
  eq(h:binding(), nil)
end)

test("failed split is not retried until layout changes", function()
  local h = fake.new()
  h.fail_split = true
  h:start()
  h:settle()
  h.fail_split = false
  h:settle()
  eq(#h.splits, 0)
  h.tab.height = 45
  h:settle()
  assert(h:status())
end)

test("closing owner and status together removes orphaned binding", function()
  local h = start()
  h:remove(h:status())
  h:remove(h.main)
  h:tick()
  eq(h:binding(), nil)
  eq(#h.close_commands, 0)
  h:assert_no_errors()
end)

test("failed close is retried with its original ID", function()
  local h = start()
  h.fail_close = true
  h:shell()
  h:tick(1)
  eq(#h.close_commands, 0)
  h.fail_close = false
  h:tick(2)
  eq(h.close_commands[1][6], tostring(h:status().id))
end)

test("missing mux IDs reported as errors are treated as missing", function()
  local h = start()
  h.missing_raises = true
  h:remove(h:status())
  h:settle()
  eq(h:status(), nil)
  eq(h:binding().suppressed, true)
end)

test("schema 7 migration adopts only verified placeholder", function()
  local h = start()
  local status = h:status()
  status.user_vars = {}
  h.wezterm.GLOBAL.codex_statusline_state = { schema = 7,
    tabs = { ["7:1"] = { main_pane_id = h.main.id, status_pane_id = status.id } }, panes = {} }
  h:reload()
  h:settle()
  eq(h:status(), status)
  assert(status.user_vars.codex_statusline_owner)
  eq(#h.splits, 1)
end)

test("corrupt legacy owner identity cannot close ordinary pane", function()
  local h = fake.new()
  h.wezterm.GLOBAL.codex_statusline_state = { schema = 7,
    tabs = { ["7:1"] = { main_pane_id = 1, status_pane_id = 1 } } }
  h:settle()
  eq(#h.close_commands, 0)
  assert(h.panes[1])
end)

test("marker recovery after state loss does not duplicate status", function()
  local h = start()
  local status = h:status()
  h.wezterm.GLOBAL.codex_statusline_state = nil
  h:reload()
  h:settle()
  eq(h:status(), status)
  eq(#h.splits, 1)
end)

test("repeated setup registers one handler per Lua context", function()
  local h = fake.new()
  require("codex_statusline").setup(h.options)
  eq(h.events["update-status"], 1)
  eq(h.wezterm.GLOBAL.codex_statusline_state, nil)
end)

test("fifty create and close cycles conserve all terminal rows", function()
  local h = fake.new()
  for i = 1, 50 do
    h:start()
    h:settle()
    assert(h:status())
    eq(h.main.dimensions.viewport_rows + h:status().dimensions.viewport_rows + 1, h.tab.height)
    h:shell()
    h:tick(1)
    h:complete_close()
    h:tick()
    eq(h.main.dimensions.viewport_rows, h.tab.height)
  end
  h:assert_no_errors()
end)

test("snapshot failure invalidates previous debounce samples", function()
  local h = fake.new()
  h:start()
  h:tick(0)
  h:tick(0.5)
  h.fail_snapshot = true
  h:tick(5)
  h.fail_snapshot = false
  h:tick(0.5)
  eq(#h.splits, 0)
  h:tick(1)
  eq(#h.splits, 1)
end)

test("recovered status with unknown owner is not collected", function()
  local h = start()
  local status = h:status()
  h.main.mode, h.main.title = "unknown", "pwsh.exe"
  h.wezterm.GLOBAL.codex_statusline_state = nil
  h:reload()
  h:settle()
  eq(h:status(), status)
  eq(#h.close_commands, 0)
end)

test("close retry revalidates ownership marker", function()
  local h = start()
  h:shell()
  h:tick(1)
  local status = h:status()
  status.user_vars = {}
  h:tick(3)
  eq(#h.close_commands, 1)
  eq(h:status(), status)
end)

test("missing GUI socket never falls back to another instance", function()
  local h = start()
  h.socket = nil
  h:shell()
  h:settle()
  eq(#h.close_commands, 0)
  assert(h:status())
end)

test("split yielding to another window cannot overlap state writes", function()
  local h = fake.new()
  h.on_split = function()
    local other = setmetatable({ id = 9 }, { __index = h.window })
    h.callbacks["update-status"](other, h.main)
    h.callbacks["window-resized"](h.window)
  end
  h:start()
  h:settle()
  eq(#h.splits, 1)
  eq(h:binding().window_id, "7")
  h:assert_no_errors()
end)

print("statusline scenario tests passed (" .. count .. " scenarios)")
